aliases:
    fleeks: cd ~/.local/share/fleek
bling: high
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
name: Fleek Configuration
packages:
    - helix
    - git
    - docker
    - ffmpeg
    - vim
    - curl
    - gzip
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      hostname: ANS-A588
      os: linux
      username: josssparkes
unfree: true
