aliases:
    fleeks: cd /home/josssparkes/.local/share/fleek
bling: default
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: false
    autopull: false
    autopush: false
    enabled: false
name: Fleek Configuration
packages:
    - helix
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      hostname: ANS-A588
      os: linux
      username: josssparkes
unfree: true
